### ISSUE TITLE
install err

### ISSUE THREAD

**Issue by dbwamgod** [bitmain-frontend/huge-tree#4]
λ npm i @bitmain/components-tree
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in

**Comment by lizhuang93** [comment]
> λ npm i @bitmain/components-tree
> npm ERR! cb() never called!
> 
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR! https://github.com/npm/npm/issues
> 
> npm ERR! A complete log of this run can be found in

使用 yarn add @bitmain/components-tree -D 试试？
