### ISSUE TITLE
默认选中不支持吗？

### ISSUE THREAD

**Issue by xiaoxian521** [bitmain-frontend/huge-tree#5]
应该少了个每个树节点用来作为唯一标识的属性

**Comment by xiaoxian521** [comment]
node-key是不是没有呢？

**Comment by xiaoxian521** [comment]
大佬 能回复下吗？

**Comment by lizhuang93** [comment]
> 大佬 能回复下吗？

**Comment by lizhuang93** [comment]
> 应该少了个每个树节点用来作为唯一标识的属性

id 就是唯一标识呀。

**Comment by lizhuang93** [comment]
属性 defaultCheckedKeys 是id组成的数组，支持默认选中啊，
方法 setCheckedKeys， 参数也是id组成的数组，
都可以选中
详细文档： https://github.com/bitmain-frontend/huge-tree/tree/master/src/library/components/hugeTree/demo
